### ISSUE TITLE
Unable to Export to Excel using Aspose.cells.dll

### ISSUE THREAD

**Issue by singhksandeep** [aspose-cells/Aspose.Cells-for-.NET#38]
Hi Team,

I am unable to export the data in an .xlsx. The data size is huge(around 25000 and above). I tried 2 cells dlls. (8.5.1.0 and 8.8.2.0) . 

Source: Aspose.Cells
TargetSite: Void AutoFitColumn(Int32)
Message: Invalid column index.

Attaching the code snippet and blank page snap.

Please assist
[code snippet.txt](https://github.com/aspose-cells/Aspose.Cells-for-.NET/files/331704/code.snippet.txt)
![snap](https://cloud.githubusercontent.com/assets/20127192/16337281/d3c57e9e-3a31-11e6-9860-e2dd9a65d2b9.png)

**Comment by babar-raza** [comment]
Hi, 

I am afraid, we require an executable standalone sample application to replicate the said issue on our side therefore please create a console application with dynamically created data source and share it in Aspose.Cells support forum on your following thread for detailed investigation.
