### ISSUE TITLE
Aspose.Cells for Android via Xamarin？

### ISSUE THREAD

**Issue by ghd258** [aspose-cells/Aspose.Cells-for-.NET#50]
Aspose.Cells for Android via Xamarin？

**Comment by shakeel-faiz** [comment]
It is not available as yet but it will be finally available however Aspose.Cells for Android via Java is available.

**Comment by shakeel-faiz** [comment]
Aspose.Cells for .NET supports Xamarin Platform since 18.2. All future versions like 18.3, 18.4, 18.5 and onward will support it.
