### ISSUE TITLE
Aspose.Cells 是否支持 NET CORE 2

### ISSUE THREAD

**Issue by ghd258** [aspose-cells/Aspose.Cells-for-.NET#51]
Aspose.Cells 是否支持 NET CORE 2

**Comment by shakeel-faiz** [comment]
We have a plan for Aspose.Cells for .NET Core but at the moment, there is no ETA for it.

**Comment by shakeel-faiz** [comment]
We have supported the .NET Core from 18.2. However, please wait for March release i.e. 18.3 as we areto do some more enhancements and fixes.
