### ISSUE TITLE
Width of column not changing after setting the cells set width property

### ISSUE THREAD

**Issue by anirudhsamudrala** [aspose-cells/Aspose.Cells-for-.NET#53]
I tried the following ways to change the width of second column in my worksheet.But nothing worked.I seee that hte width is still the same as before. Is there something I am missing?

w.Cells.SetColumnWidthPixel(2, 10);  
w.Cells.SetColumnWidthInch(2, 10);
w.Cells.SetColumnWidth(2, 10);

**Comment by shakeel-faiz** [comment]
We have tested this issue and found, it is working fine. Please note, index starts from 0, so 0 means 1st column, 1 means second column, 2 means third and 3 means fourth column etc. 

Please execute the following code. You can see the effect of this code on the output Excel file in the following screenshot. 

**C#**

```
//Create workbook
Workbook wb = new Workbook();

//Access first worksheet
Worksheet w = wb.Worksheets[0];

//Please note index in Cells start from 0
//It means, 0 is first column, 1 is second column, 2 is third column etc.

//Change the second column width - 100 pixels
w.Cells.SetColumnWidthPixel(1, 100);

//Change the third column width - 3 inches
w.Cells.SetColumnWidthInch(2, 3);

//Change the fourth column width - 25 units
w.Cells.SetColumnWidth(3, 25);

//Save the output Excel file
wb.Save("output.xlsx");
```

**Screenshot**
https://i.imgur.com/2ZoBm93.png
