### ISSUE TITLE
How to Generate Column Charts with Folded Lines. 

### ISSUE THREAD

**Issue by ksq1063126847** [aspose-cells/Aspose.Cells-for-.NET#57]
1. **Here's what I want**, 
![Result](https://user-images.githubusercontent.com/14009784/65004531-4a9cef80-d92f-11e9-99a6-4146b56c643e.png)

2.**but what I actually get.** 
![actual](https://user-images.githubusercontent.com/14009784/65004579-78823400-d92f-11e9-9d73-94c0036775f5.png)

3. Here is  the code.

public static void Run()
{
            // Instantiating a Workbook object
            Workbook workbook = new Workbook();

            // Obtaining the reference of the newly added worksheet by passing its sheet index
            Worksheet worksheet = workbook.Worksheets[0];

            // Adding sample values to cells
            worksheet.Cells["A1"].PutValue("Product");
            worksheet.Cells["A2"].PutValue("A");
            worksheet.Cells["A3"].PutValue("B");
            worksheet.Cells["A4"].PutValue("C");
            worksheet.Cells["A5"].PutValue("D");

            worksheet.Cells["B1"].PutValue("Count");
            worksheet.Cells["B2"].PutValue(1);
            worksheet.Cells["B3"].PutValue(2);
            worksheet.Cells["B4"].PutValue(3);
            worksheet.Cells["B5"].PutValue(4);

            worksheet.Cells["C1"].PutValue("Percent");
            worksheet.Cells["C2"].PutValue(0.1);
            worksheet.Cells["C3"].PutValue(0.2);
            worksheet.Cells["C4"].PutValue(0.3);
            worksheet.Cells["C5"].PutValue(0.4);

            // Adding a chart to the worksheet
            int chartIndex = worksheet.Charts.Add(Aspose.Cells.Charts.ChartType.Column, 5, 0, 25, 10);

            // Accessing the instance of the newly added chart
            Aspose.Cells.Charts.Chart chart = worksheet.Charts[chartIndex];

            // Adding NSeries (chart data source) to the chart ranging from "A1" cell to "C5"
            chart.NSeries.Add("A1:C5", true);

            // Setting the chart type of 2nd NSeries to display as line chart
            chart.NSeries[1].Type = Aspose.Cells.Charts.ChartType.Column;
            chart.NSeries[2].Type = Aspose.Cells.Charts.ChartType.Line;

            chart.SecondValueAxis.IsVisible = true;
            
            // Saving the Excel file
            //workbook.Save(outputDir + "outputHowToCreateCustomChart.xlsx");
            workbook.Save( "F:\\outputHowToCreateCustomChart.xlsx");

            Console.WriteLine("HowToCreateCustomChart executed successfully.");
        }

**Comment by ksq1063126847** [comment]
Brothers，help me！

**Comment by ksq1063126847** [comment]
### This is the solution.

###  1. All code 

public static void Run()
        {
            // Instantiating a Workbook object
            Workbook workbook = new Workbook();

            // Obtaining the reference of the newly added worksheet by passing its sheet index
            Worksheet worksheet = workbook.Worksheets[0];

            // Adding sample values to cells
            worksheet.Cells["A1"].PutValue("Product");
            worksheet.Cells["A2"].PutValue("A");
            worksheet.Cells["A3"].PutValue("B");
            worksheet.Cells["A4"].PutValue("C");
            worksheet.Cells["A5"].PutValue("D");

            worksheet.Cells["B1"].PutValue("Count");
            worksheet.Cells["B2"].PutValue(1);
            worksheet.Cells["B3"].PutValue(2);
            worksheet.Cells["B4"].PutValue(3);
            worksheet.Cells["B5"].PutValue(4);

            worksheet.Cells["C1"].PutValue("Percent");
            worksheet.Cells["C2"].PutValue(0.1);
            worksheet.Cells["C3"].PutValue(0.2);
            worksheet.Cells["C4"].PutValue(0.3);
            worksheet.Cells["C5"].PutValue(0.4);

            // Adding a chart to the worksheet
            int chartIndex = worksheet.Charts.Add(Aspose.Cells.Charts.ChartType.Column, 5, 0, 25, 10);

            // Accessing the instance of the newly added chart
            Aspose.Cells.Charts.Chart chart = worksheet.Charts[chartIndex];

            // Adding NSeries (chart data source) to the chart ranging from "B2" cell to "C5"
            chart.NSeries.Add("B2:C5", true);

            // Setting the chart type of 2nd NSeries to display as line chart
            chart.NSeries[0].Type = Aspose.Cells.Charts.ChartType.Column;
            chart.NSeries[1].Type = Aspose.Cells.Charts.ChartType.LineStackedWithDataMarkers;

            //设置 NSeries列名称
            chart.NSeries.CategoryData = "A2:A5";
            chart.NSeries[0].Name = "Product";
            chart.NSeries[1].Name = "Percent";

            //设置第二坐标轴
            chart.NSeries[1].PlotOnSecondAxis = true;
            chart.SecondValueAxis.IsVisible = true;

            //显示DataTable
            chart.ShowDataTable = true;
          
            // Saving the Excel file
            workbook.Save(outputDir + "outputHowToCreateCustomChart.xlsx");

            Console.WriteLine("HowToCreateCustomChart executed successfully.");
        }


###  2.Screenshot


![Ok](https://user-images.githubusercontent.com/14009784/65017505-88167280-d959-11e9-9b2e-82dfe20f8be5.png)

**Comment by amjad-sahi** [comment]
Good to know that you have sorted it out now. Your chart is custom oriented which is a combination of two charts (Column and Line), so you have to write the code accordingly.
