### ISSUE TITLE
How to remain "empty column" when use `excel to json`

### ISSUE THREAD

**Issue by awxiaoxian2020** [aspose-cells/Aspose.Cells-for-.NET#63]
![3](https://user-images.githubusercontent.com/69554233/193489297-baa9dd79-8d24-4026-b7c7-dcfa952df5e9.png)

![4](https://user-images.githubusercontent.com/69554233/193489648-b1df224d-6b03-46a3-8da1-bdd3652cef77.png)

The last two columns have no values ​​and I want to keep empty strings in the json.

**Comment by amjad-sahi** [comment]
@awxiaoxian2020,

Please try the following sample code to accomplish your task. You may use [ExportRangeToJsonOptions](https://reference.aspose.com/cells/net/aspose.cells.utility/exportrangetojsonoptions) and [JsonUtility](https://reference.aspose.com/cells/net/aspose.cells.utility/jsonutility) classes to save your desired data range (including empty columns) to JSON data:
e.g.
**Sample code:**
```cs
//Load your source workbook
Workbook workbook = new Workbook("e:\\test2\\book1.xlsx");

// Set ExportRangeToJsonOptions
Aspose.Cells.Utility.ExportRangeToJsonOptions options = new Aspose.Cells.Utility.ExportRangeToJsonOptions();
//Include empty cells
options.ExportEmptyCells = true;

//Get the first worksheet
Worksheet worksheet = workbook.Worksheets[0];
//Create data range including empty cells in those columns
Range range = worksheet.Cells.CreateRange(0, 0, worksheet.Cells.MaxDataRow + 1, worksheet.Cells.MaxDataColumn + 1);
//Get the Json data
string data = Aspose.Cells.Utility.JsonUtility.ExportRangeToJson(range, options);

Console.WriteLine(data); 
```
Hope, this helps a bit. 

We also encourage you to kindly post your queries, comments or issue in dedicated [forums](https://forum.aspose.com/c/cells/9).
